name: Cypress Tests firefox

on:
  push:
    branches:
      - main
 # pull_request:

env:
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        firefox-version: [latest] # Test against multiple Firefox versions
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set up firefox
      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox-version}}

      # Step 5: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --browser firefox  

      - name: Run Cypress marged tests
        run: |
          npx mochawesome-merge "cypress/results/*.json" > mochawesome.json
          npx marge mochawesome.json

      # Step 6: Upload Cypress videos and screenshots (optional)
      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            mochawesome-report/